---
services:
  rabbitmq:
    build: rabbitmq
    ports:
      - "61613:61613"
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: guest@guest.com
      PGADMIN_DEFAULT_PASSWORD: guest
    depends_on:
      database:
        condition: service_healthy
  database:
    tty: true
    build: postgres
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=groupbuy'
      - 'POSTGRES_USER=gbadmin'
      - 'POSTGRES_PASSWORD=gbpassword'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gbadmin -d groupbuy"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  frontend:
    tty: true
    build: frontend
    # Per dev
    volumes:
      - './frontend/src:/home/node/app/src'
    ports:
      - "4200:4200"
    depends_on:
      database:
        condition: service_healthy
