---
services:
  database:
    build: postgres
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=groupbuy'
      - 'POSTGRES_USER=gbadmin'
      - 'POSTGRES_PASSWORD=gbpassword'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gbadmin -d groupbuy"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build: frontend
    ports:
      - "4200:4200"
    depends_on:
      database:
        condition: service_healthy
